let releases = [
        /* THIS IS A TEMPLATE - PLEASE COPY PASTE FROM { TO }, 
    { date : '',
    id : 'CSMD111',
    genre : '',
    artist : '',
    name : '',
    imageurl : '',
    beatporturl : '',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
}, */

    { date : '17-06-2019',
    id : 'CSMD111',
    genre : 'melodic techno',
    artist : 'Manic Brothers, Alpha Particle Assembly',
    name : 'Terraform',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/95d36db2-1149-4f9e-84d2-89af4bba1beb.jpg',
    beatporturl : 'https://www.beatport.com/release/terraform/2613601',
    spotifyurl : 'https://open.spotify.com/album/0nS7sPR8cy3DR1rOyT4r1j',
    deezerurl : 'https://soundcloud.com/consumed-music/sets/manic-brothers-alpha-particle',
    appleurl : 'https://music.apple.com/us/album/terraform-single/1466299788',
    soundcloudurl : 'https://soundcloud.com/consumed-music/sets/manic-brothers-alpha-particle',
    embedurl1 : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/629667141&color=%238a3131&inverse=true&auto_play=false&show_user=false',
    embedurl2 : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/629670513&color=%238a3131&inverse=true&auto_play=false&show_user=false',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
    },
    { date : '25-12-2018',
    id : 'CSMD110',
    genre : 'melodic techno',
    artist : 'Alpha Particle Assembly',
    name : 'Future',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/b4565d59-2366-4ea1-bcf0-9876b0c44c6d.jpg',
    beatporturl : 'https://www.beatport.com/release/future/2469173',
    spotifyurl : 'https://open.spotify.com/album/2rqOTgTePFrpwQ8j2DVOdH',
    deezerurl : 'https://www.deezer.com/sv/album/82050592',
    appleurl : 'https://itunes.apple.com/us/album/future-single/1446984915',
    soundcloudurl : 'https://soundcloud.com/consumed-music/sets/alpha-particle-assembly-future',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
    },
    { date : '15-11-2018',
    id : 'CSMD109',
    genre : 'melodic techno',
    artist : 'Mihalyz',
    name : 'Nature of Reality',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/1e79e495-90e9-4fb6-9449-1b8ff0f94303.jpg',
    beatporturl : 'https://www.beatport.com/release/nature-of-reality/2432298',
    spotifyurl : 'https://open.spotify.com/album/0FAnn89h22oIFq2djwBY0v',
    deezerurl : 'https://www.deezer.com/sv/album/77733212',
    appleurl : 'https://itunes.apple.com/us/album/nature-of-reality-ep/1441256483',
    soundcloudurl : 'https://soundcloud.com/consumed-music/sets/mihalyz-nature-of-reality',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
    },
    { date : '28-09-2018',
    id : 'CSMD108',
    genre : '',
    artist : 'Lolla Tek, Mikel Gil',
    name : 'Ghost Protocol',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/2c5ea4e0-5160-4a98-94b1-757a18b7d5e8.jpg',
    beatporturl : 'https://www.beatport.com/release/ghost-protocol/2385004',
    spotifyurl : 'https://open.spotify.com/album/2VwHcMIHzu52o2GkVOuJqi',
    deezerurl : 'https://www.deezer.com/sv/album/72453042',
    appleurl : 'https://itunes.apple.com/us/album/ghost-protocol-single/1435370323',
    soundcloudurl : 'https://soundcloud.com/consumed-music/sets/lolla-tek-mikel-gil-ghost',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
    },
    { date : '13-08-2018',
    id : 'CSMD107',
    genre : '',
    artist : 'Jeancy',
    name : 'Particles & Waves',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/3f520af7-c722-48bc-876d-4691cac5bb2f.jpg',
    beatporturl : 'https://www.beatport.com/release/particles-and-waves/2352860',
    spotifyurl : 'https://open.spotify.com/album/7sHtQEtXWzT7Nq9NUHUHU0',
    deezerurl : 'https://www.deezer.com/sv/album/69171912',
    appleurl : 'https://itunes.apple.com/us/album/particles-waves-single/1417452777',
    soundcloudurl : 'https://soundcloud.com/consumed-music/sets/jeancy-particles-waves',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
    },
    { date : '18-06-2018',
    id : 'CSMD106',
    genre : '',
    artist : 'Kalden Bess',
    name : 'Basic',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/3836dcad-0580-4ce9-9a07-993ab090192a.jpg',
    beatporturl : 'https://www.beatport.com/release/basic/2304869',
    spotifyurl : 'https://open.spotify.com/album/2fyImgZtdyZdCiWnF9qObD',
    deezerurl : 'https://www.deezer.com/sv/album/64649882',
    appleurl : 'https://itunes.apple.com/us/album/basic/1390709090',
    soundcloudurl : 'https://soundcloud.com/consumed-music/sets/kalden-bess-undfnd-prml',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
    },
    { date : '11-05-2018',
    id : 'CSMD105',
    genre : '',
    artist : 'Alpha Particle Assembly',
    name : 'Iso II',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/0d04e4d7-5e17-4fa0-bd87-22a4f3d29813.jpg',
    beatporturl : 'https://www.beatport.com/release/iso-ii/2254062',
    spotifyurl : 'https://open.spotify.com/album/47nxCQslwsr9m03t4tjP6H',
    deezerurl : 'https://www.deezer.com/sv/album/59793232',
    appleurl : 'https://itunes.apple.com/us/album/iso-ii-single/1363745374',
    soundcloudurl : 'https://soundcloud.com/consumed-music/sets/alpha-particle-assembly-iso',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
    }, 
    { date : '09-04-2018',
    id : 'CSMD104',
    genre : '',
    artist : 'Lewis Delay',
    name : 'Unafraid of Future',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/b1e6f582-6560-411b-b9cc-ea1efc9a3ab8.jpg',
    beatporturl : 'https://www.beatport.com/release/unafraid-of-future/2254111',
    spotifyurl : 'https://open.spotify.com/album/7ISaaDSMAqJLhWK45dasSV',
    deezerurl : 'https://www.deezer.com/sv/album/59659482',
    appleurl : 'https://itunes.apple.com/mt/album/unafraid-of-future-single/1363210153',
    soundcloudurl : 'https://soundcloud.com/consumed-music/sets/lewis-delay-unafraid-of',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
        }, 
    { date : '05-02-2018',
    id : 'CSMD103',
    genre : '',
    artist : 'Alpha Particle Assembly',
    name : 'Perpetual Motion',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/5764b94f-2a54-4258-90d5-568020b581e6.jpg',
    beatporturl : 'https://www.beatport.com/release/perpetual-motion/2198553',
    spotifyurl : 'https://open.spotify.com/album/0iO7aHJRf3OCelOeZrib8U',
    deezerurl : 'https://www.deezer.com/sv/album/55022892',
    appleurl : 'https://itunes.apple.com/us/album/perpetual-motion/1335535426',
    soundcloudurl : 'https://soundcloud.com/consumed-music/sets/alpha-particle-assembly',
    embedurl1 : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/372732746&color=%238a3131&inverse=true&auto_play=false&show_user=false',
    embedurl2 : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/382729322&color=%238a3131&inverse=true&auto_play=false&show_user=false',
    embedurl3 : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/382734863&color=%238a3131&inverse=true&auto_play=false&show_user=false',
    embedurl4 : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/382716518&color=%238a3131&inverse=true&auto_play=false&show_user=false',
    embedurl5 : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/382725260&color=%238a3131&inverse=true&auto_play=false&show_user=false',
    embedurl6 : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/382737440&color=%238a3131&inverse=true&auto_play=false&show_user=false',
    embedurl7 : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/382726757&color=%238a3131&inverse=true&auto_play=false&show_user=false',
    embedurl8 : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/382738760&color=%238a3131&inverse=true&auto_play=false&show_user=false',
    embedurl9 : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/382732649&color=%238a3131&inverse=true&auto_play=false&show_user=false',
    embedurl10 : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/382740071&color=%238a3131&inverse=true&auto_play=false&show_user=false',
    },
    { date : '13-11-2017',
    id : 'CSMD101',
    genre : '',
    artist : 'Felix Kroecher',
    name : 'You Don\'t know but Remixes',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/276f3578-84fe-4e6f-a1a7-7ced3cdf0c3b.jpg',
    beatporturl : 'https://www.beatport.com/release/you-dont-know-but/2143479',
    spotifyurl : 'https://open.spotify.com/album/1AmTE9ZCjm7DaUF7FhLbt3',
    deezerurl : 'https://www.deezer.com/sv/album/50802162',
    appleurl : 'https://itunes.apple.com/it/album/you-dont-know-but/1300717635?l=en',
    soundcloudurl : 'https://soundcloud.com/consumed-music/sets/felix-krocher-you-dont-know-2',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
    },
    { date : '08-01-2017',
    id : 'CSMD100',
    genre : '',
    artist : 'Bulaklak',
    name : 'Hate Me',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/27f24ebe-d776-4a94-9782-d37d7e60a21d.jpg',
    beatporturl : 'https://www.beatport.com/release/hate-me/2072951',
    spotifyurl : 'https://open.spotify.com/album/01wCp2JTELQukc4x6rv575',
    deezerurl : 'https://www.deezer.com/sv/album/44833551',
    appleurl : 'https://itunes.apple.com/us/album/hate-me-single/1260563607',
    soundcloudurl : 'https://soundcloud.com/consumed-music/sets/csmd099-bulaklak-hate-me-ep',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
    },
    { date : '03-07-2017',
    id : 'CSMD099',
    genre : '',
    artist : 'Mark Mywords, A++',
    name : 'Control Your Mind',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/cf6aa9bc-a753-46f7-bff1-ca8d8776bf21.jpg',
    beatporturl : 'https://www.beatport.com/release/control-your-mind/2051101',
    spotifyurl : 'https://open.spotify.com/album/0Hwqt9hdQfLLqpFvn8LWWP',
    deezerurl : 'https://www.deezer.com/sv/album/43329091',
    appleurl : 'https://itunes.apple.com/ca/album/control-your-mind-single/1249797098',
    soundcloudurl : 'https://soundcloud.com/consumed-music/sets/csmd098-a-mark-mywords-control',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
    },
    { date : '05-06-2017',
    id : 'CSMD098',
    genre : '',
    artist : 'A++',
    name : 'Drones Awakening',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/5d413568-34a1-4a29-9094-808e2c3bc688.jpg',
    beatporturl : 'https://www.beatport.com/release/drones-awakenings/2025179',
    spotifyurl : 'https://open.spotify.com/album/1dXvNRdEAS7WFyHgZtzjLg',
    deezerurl : 'https://www.deezer.com/fr/album/41615201',
    appleurl : 'https://itunes.apple.com/cy/album/drones-awakenings-single/1236949308',
    soundcloudurl : 'https://soundcloud.com/consumed-music/sets/csmd097-a-drones-awakenings',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
    },
    { date : '24-04-2017',
    id : 'CSMD097',
    genre : '',
    artist : 'Kreisel, Sisko Electrofanatik',
    name : 'Octopus The Remixes',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/012b558b-22b3-43ad-a33e-52c17d010c6d.jpg',
    beatporturl : 'https://www.beatport.com/release/kreisel-sisko-electrofanatik/1999768',
    spotifyurl : 'https://open.spotify.com/album/7CYp0eNtS8Of0V4lHBkG4X',
    deezerurl : 'https://www.deezer.com/fr/album/39676871',
    appleurl : 'https://itunes.apple.com/us/album/kreisel-sisko-electrofanatik/1225484845',
    soundcloudurl : 'https://soundcloud.com/consumed-music/sets/csmd096-kreisel-sisko',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
    },
    { date : '03-04-2017',
    id : 'CSMD096',
    genre : '',
    artist : 'German Valley',
    name : 'False Illusion',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/c4183541-2c5d-4f5d-a9b7-b3828b105aee.jpg',
    beatporturl : 'https://www.beatport.com/release/false-illusion/1983974',
    spotifyurl : 'https://open.spotify.com/album/22P23lglgirF7rXoR2ZKZh',
    deezerurl : 'https://www.deezer.com/fr/album/15700772',
    appleurl : 'https://itunes.apple.com/ca/album/false-illusion-single/1218142700',
    soundcloudurl : 'https://soundcloud.com/consumed-music/sets/consumed-music-best-of-4-years',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
    },
    { date : '31-03-2017',
    id : 'CSMD095',
    genre : '',
    artist : 'A++, Lolla Tek',
    name : '9nemy the Remixes',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/37f33214-057d-485d-9a76-7073dd28c10e.jpg',
    beatporturl : 'https://www.beatport.com/release/9nemy-the-remixes/1977653',
    spotifyurl : 'https://open.spotify.com/album/76gcE8g9K4p7Gfw1E6Hj7F',
    deezerurl : 'https://www.deezer.com/fr/album/15619262',
    appleurl : 'https://itunes.apple.com/gb/album/9nemy-the-remixes-ep/1215275925',
    soundcloudurl : 'https://soundcloud.com/consumed-music/sets/csmd095-a-lolla-tek-the',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
    },
    { date : '20-03-2017',
    id : 'CSMD094',
    genre : '',
    artist : 'Rosper',
    name : 'Signal Frequency',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/c9562cb3-dc12-47a1-b375-d668d839d4f0.jpg',
    beatporturl : 'https://www.beatport.com/release/signal-frequency/1972313',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
    },
    { date : '27-02-2017',
    id : 'CSMD093',
    genre : '',
    artist : 'Cr3s',
    name : 'Mind Mapper',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/1dacded8-709b-4fa5-bb99-84b4161eb07c.jpg',
    beatporturl : 'https://www.beatport.com/release/mind-mapper/1957972',
    spotifyurl : 'https://open.spotify.com/album/4ID0GzqUpWzkSjW58ucnnX',
    deezerurl : 'https://www.deezer.com/fr/album/15361247',
    appleurl : 'https://itunes.apple.com/us/album/mind-mapper/1205855724',
    soundcloudurl : 'https://soundcloud.com/consumed-music/sets/cr3s-mind-mapper-ep',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
    },
    { date : '10-02-2017',
    id : 'CSMD092',
    genre : '',
    artist : 'Fractious',
    name : 'Transpire the Remixes',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/f2a6405f-d1cc-42d9-b822-a73e1599607b.jpg',
    beatporturl : 'https://www.beatport.com/release/transpire-the-remixes/1939620',
    spotifyurl : 'https://open.spotify.com/album/4RnXAQW8p6H9lIKKuVwPhA',
    deezerurl : 'https://www.deezer.com/fr/album/15142121',
    appleurl : 'https://itunes.apple.com/us/album/transpire-the-remixes/id1198454095',
    soundcloudurl : 'https://soundcloud.com/consumed-music/sets/csmd092-fractious-transpire',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
    },
    { date : '30-01-2017',
    id : 'CSMD091',
    genre : '',
    artist : 'Devid Dega, 9nemy',
    name : 'Insider',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/25410ecc-7038-4954-89c6-51f22031ceae.jpg',
    beatporturl : 'https://www.beatport.com/release/insider/1936149',
    spotifyurl : 'https://open.spotify.com/album/7lXhuLazvfiDZL686Hm3V9',
    deezerurl : 'https://www.deezer.com/fr/album/15092387',
    appleurl : 'https://itunes.apple.com/us/album/insider-single/1197794357',
    soundcloudurl : 'https://soundcloud.com/consumed-music/sets/csmd091-devid-dega-9nemy',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
    },
    { date : '09-01-2017',
    id : 'CSMD090',
    genre : '',
    artist : 'Kreisel, Sisko Electrofanatik',
    name : 'Octopus',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/beb7eb26-6774-4759-80f4-8e24b0fac650.jpg',
    beatporturl : 'https://www.beatport.com/release/octopus/1926103',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
    },
    { date : '29-12-2016',
    id : 'CSMD089',
    genre : '',
    artist : 'Loui Fernandez',
    name : 'Force',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/598eaae9-36db-40e1-8321-32c5a1a42ce8.jpg',
    beatporturl : 'https://www.beatport.com/release/force/1917772',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
    },
    { date : '26-12-2016',
    id : 'CSMD088',
    genre : '',
    artist : 'Lee View',
    name : 'Metamorfoza',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/c835be29-fea5-447e-af8c-1f552c8f8749.jpg',
    beatporturl : 'https://www.beatport.com/release/metamorfoza/1917812',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
    },
    { date : '21-10-2016',
    id : 'CSMD087',
    genre : '',
    artist : 'Albert Silver',
    name : 'Decoded Thoughts',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/a762abaa-a100-4b86-828a-2d480da364f9.jpg',
    beatporturl : 'https://www.beatport.com/release/decoded-thoughts/1863081',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
    { date : '19-10-2016',
    id : 'CSMD086',
    genre : '',
    artist : 'Steve Mulder',
    name : 'Paradise',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/983a6d6c-84df-4943-a2e7-f4969f601112.jpg',
    beatporturl : 'https://www.beatport.com/release/paradise/1863214',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
    { date : '30-09-2016',
    id : 'CSMD085',
    genre : '',
    artist : 'Sonate',
    name : 'Yellow Beans',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/9c7fc490-1050-4554-9c4d-f2f6a747c56e.jpg',
    beatporturl : 'https://www.beatport.com/release/yellow-beans/1840783',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
    { date : '23-09-2016',
    id : 'CSMD084',
    genre : '',
    artist : 'Lolla Tek',
    name : 'Renegade',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/6c312688-3cdd-4f7d-a82b-42dcaae8a28b.jpg',
    beatporturl : 'https://www.beatport.com/release/renegade/1836275',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
    { date : '16-09-2016',
    id : 'CSMD083',
    genre : '',
    artist : 'A++ & Mircea Ivan',
    name : 'Deformation',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/675298c8-db17-4b55-bc66-9fe7faf31113.jpg',
    beatporturl : 'https://www.beatport.com/release/deformation/1834303',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
    { date : '02-09-2016',
    id : 'CSMD082',
    genre : '',
    artist : 'Marc Galindo',
    name : 'Under Control (9NEMY Remix)',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/6144dbfa-2a44-4b1b-a9ff-bb374cc14f83.jpg',
    beatporturl : 'https://www.beatport.com/release/under-control-9nemy-remix/1832963',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
    { date : '15-08-2016',
    id : 'CSMD081',
    genre : '',
    artist : 'Alex Smott, Kostha, Elio Kenza',
    name : 'Rennek',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/8765bedd-bd87-4fe6-a45f-cb97ad3799f5.jpg',
    beatporturl : 'https://www.beatport.com/release/rennek/1817564',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
    { date : '08-08-2016',
    id : 'CSMD080',
    genre : '',
    artist : 'Cristian Arango',
    name : 'The One',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/354ef8c5-b07a-4437-b05a-c62b27303eba.jpg',
    beatporturl : 'https://www.beatport.com/release/the-one/1816828',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
    { date : '29-07-2016',
    id : 'CSMD079',
    genre : '',
    artist : 'Devid Dega',
    name : 'K.O.',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/2793ae44-1c21-4789-961b-a14c0f7d9650.jpg',
    beatporturl : 'https://www.beatport.com/release/k-o/1802171',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
    { date : '20-07-2016',
    id : 'CSMD078',
    genre : '',
    artist : 'A++',
    name : 'Hybrid',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/52821f5b-9b02-4145-8700-c5dc2cba9fbf.jpg',
    beatporturl : 'https://www.beatport.com/release/hybrid/1797144',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
    { date : '14-07-2016',
    id : 'CSMD0771',
    genre : '',
    artist : 'De Dirigenten',
    name : 'Stranger',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/4e00342f-486c-4f40-ab4f-27b4c4338ff8.jpg',
    beatporturl : 'https://www.beatport.com/release/stranger/1805618',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
    { date : '11-07-2016',
    id : 'CSMD077',
    genre : '',
    artist : 'Ovi M',
    name : 'Psycho',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/fb462b4c-468b-4279-82ac-1fa76bc2b8c5.jpg',
    beatporturl : 'https://www.beatport.com/release/psycho/1796374',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
{ date : '24-06-2016',
    id : 'CSMD076',
    genre : '',
    artist : 'Fory',
    name : 'Nebula',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/84fb7f42-4953-4ff6-b2c8-657255ec1234.jpg',
    beatporturl : 'https://www.beatport.com/release/nebula/1788274',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
{ date : '13-06-2016',
    id : 'CSMD075',
    genre : '',
    artist : 'Markus Schweickart',
    name : 'Naxos',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/cfc62eab-f758-4064-9f56-b9ecb8e30079.jpg',
    beatporturl : 'https://www.beatport.com/release/naxos/1786183',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
{ date : '19-05-2016',
    id : 'CSMD074',
    genre : '',
    artist : 'J&S Project, Richard Cleber',
    name : 'Ormes',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/516f70a3-7e56-453f-a31d-795daaab00f8.jpg',
    beatporturl : 'https://www.beatport.com/release/ormes/1768641',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
{ date : '10-05-2016',
    id : 'CSMD073',
    genre : '',
    artist : 'Loui Fernandez, Bulaklak',
    name : 'Elpidio (A++ Reconstruktion)',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/9170b8f1-0485-4d71-b715-ffb2d508a74f.jpg',
    beatporturl : 'https://www.beatport.com/release/elpidio-a-reconstruktion/1762308',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
{ date : '25-04-2016',
    id : 'CSMD072',
    genre : '',
    artist : 'J&S Project, Richard Cleber',
    name : 'Finder',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/8353e58a-c14b-4757-9dda-0c2b06a1c8fc.jpg',
    beatporturl : 'https://www.beatport.com/release/finder/1752708',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
{ date : '04-11-2016',
    id : 'CSMD070',
    genre : '',
    artist : 'Daniele Donati',
    name : 'Groove Street',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/2064c053-d0ca-4d56-9b5b-2623b17f963a.jpg',
    beatporturl : 'https://www.beatport.com/release/groove-street/1730626',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
{ date : '04-10-2016',
    id : 'CSMD071',
    genre : '',
    artist : 'The Extraverse',
    name : 'Evolet',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/f5d2cd79-e82e-470e-90fc-5eaeee7ea084.jpg',
    beatporturl : 'https://www.beatport.com/release/evolet/1729470',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
{ date : '21-03-2016',
    id : 'CSMD069',
    genre : '',
    artist : 'A++, Lolla Tek',
    name : '9Nemy: The Remixes, Vol. 1',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/6f1fd8cb-a671-41fd-a99d-0cbe072b5171.jpg',
    beatporturl : 'https://www.beatport.com/release/9nemy-the-remixes-vol-1/1732641',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
{ date : '09-03-2016',
    id : 'CSMD068',
    genre : '',
    artist : 'Fractious',
    name : 'Transpire',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/a930a28f-90c9-490d-b0d5-0116d7ea7584.jpg',
    beatporturl : 'https://www.beatport.com/release/transpire/1718523',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
{ date : '29-02-2016',
    id : 'CSMD067',
    genre : '',
    artist : 'Mr Wox',
    name : 'Distrikt',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/3c22027f-69ce-416e-a7ca-9cc46615eca7.jpg',
    beatporturl : 'https://www.beatport.com/release/distrikt/1705484',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
{ date : '23-02-2016',
    id : 'CSMD066',
    genre : '',
    artist : 'Sean Jay Dee, Daniell C',
    name : 'Inner Frequency',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/299bdba6-56fc-46ce-a332-34b1bf76044d.jpg',
    beatporturl : 'https://www.beatport.com/release/inner-frequnecy/1704402',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
{ date : '10-02-2016',
    id : 'CSMD065',
    genre : '',
    artist : 'JunkieKids',
    name : 'I Don\'t Care',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/ab556583-48a7-42da-ba17-b5c5a8049035.jpg',
    beatporturl : 'https://www.beatport.com/release/i-dont-care/1701953',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '', 
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
{ date : '02-02-2016',
    id : 'CSMD064',
    genre : '',
    artist : 'Nonyas',
    name : 'Final Sequence',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/2c015dcd-2869-4114-912f-70cfba2dc49d.jpg',
    beatporturl : 'https://www.beatport.com/release/final-sequence/1693255',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
{ date : '20-01-2016',
    id : 'CSMD063',
    genre : '',
    artist : 'Loui Fernandez, Bulaklak',
    name : 'Let It Go',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/b4686f6d-e98b-4fe3-82ef-9c09e45fa5db.jpg',
    beatporturl : 'https://www.beatport.com/release/let-it-go/1687351',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
{ date : '13-01-2016',
    id : 'CSMD062',
    genre : '',
    artist : 'Hassio (COL)',
    name : 'Romances Oil',
    imageurl : 'https://geo-media.beatport.com/image_size/250x250/af62242d-1ff7-4a36-9e76-4b21f4e1280c.jpg',
    beatporturl : 'https://www.beatport.com/release/romances-oil/1683181',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
},
    /*
    { date : '',
    id : 'CSMD111',
    genre : '',
    artist : '',
    name : '',
    imageurl : '',
    beatporturl : '',
    spotifyurl : '',
    deezerurl : '',
    appleurl : '',
    soundcloudurl : '',
    embedurl1 : '',
    embedurl2 : '',
    embedurl3 : '',
    embedurl4 : '',
    embedurl5 : '',
    embedurl6 : '',
    embedurl7 : '',
    embedurl8 : '',
    embedurl9 : '',
    embedurl10 : '',
}, */
]


export default releases;