

let supports = [
    /* THIS IS A TEMPLATE - PLEASE COPY PASTE FROM { TO }, 
    { 
        title : '',
        shortInfo : '',
        releaseid : '',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/4e5f576da9f1c2cf483ac58615e378bc0014ecc3/src/Static/SupportCovers/INSERT_FILE_NAME?raw=true',
    },*/
    { 
        title : 'Someone Else supporting CSMD004',
        shortInfo : 'Someone Else including CSMD004 in his Beatport chart ',
        releaseid : 'CSMD004',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/master/src/Static/SupportCovers/someoneElseThePlace.png?raw=true',
    },
    { 
        title : 'Steve Mulder supporting CSMD027',
        shortInfo : 'Steve Mulder including CSMD027 in his Beatport chart ',
        releaseid : 'CSMD027',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/master/src/Static/SupportCovers/MulderNebula.png?raw=true',
    },
    { 
        title : 'Spartaque supporting CSMD027',
        shortInfo : 'Spartaque including CSMD027 in his Beatport chart',
        releaseid : 'CSMD027',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/master/src/Static/SupportCovers/SpartaqueNebula.png?raw=true',
    },
    { 
        title : 'REHMARK supporting CSMD038',
        shortInfo : 'REHMARK including CSMD038 in his Beatport chart ',
        releaseid : 'CSMD038',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/master/src/Static/SupportCovers/rehmarkTeased.png?raw=true',
    },
    { 
        title : 'Veerus supports CSMD038',
        shortInfo : 'Veerus includes CSMD038 in his exclusive mix for Le Club Culture',
        releaseid : '',
        embedUrl : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/204810209&color=%236e1111&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true',
        coverUrl : '',
    },
    { 
        title : 'Steve Mulder supporting CSMD038',
        shortInfo : 'Steve Mulder includes CSMD038 in his exclusive mix for Alleanza',
        releaseid : 'CSMD038',
        embedUrl : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/208947810&color=%236e1111&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true',
        coverUrl : '',
    },
    { 
        title : 'Felix Krocher supports CSMD038',
        shortInfo : 'Felix Krochers plays in his Hardliner Podcast CSMD038 06.24.14',
        releaseid : 'CSMD038',
        embedUrl : 'https://www.mixcloud.com/widget/iframe/?hide_cover=1&feed=%2Flivesetsdjmixes%2Ffelix-kroecher-hardliner-sat-06-24-2015%2F',
        coverUrl : '',
    },
    { 
        title : 'Felix Krocher supports CSMD038 ',
        shortInfo : 'Felix Krochers plays in his Hardliner Podcast CSMD038',
        releaseid : 'CSMD038',
        embedUrl : 'https://www.mixcloud.com/widget/iframe/?hide_cover=1&feed=%2Flivesetsdjmixes%2Ffelix-kroecher-hardliner-sat-06-10-2015%2F',
        coverUrl : '',
    },
    { 
        title : 'Spartaque supports CSMD044',
        shortInfo : 'Spartaque plays CSMD044 Recorded Live at Upload Club, Off Sonar, Barcelona ',
        releaseid : 'CSMD044',
        embedUrl : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/211036544&color=%236e1111&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true',
        coverUrl : '',
    },
    { 
        title : 'Mattew Jay supports CSMD055',
        shortInfo : 'Mattew Jay includes in his Beatport chart CSMD055',
        releaseid : 'CSMD055',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/master/src/Static/SupportCovers/mattewJayHomesick.png?raw=true',
    },
    { 
        title : 'Giorgio Rusconi supporting CSMD101',
        shortInfo : 'Giorgio Rusconi including CSMD101 in his latest mix for Mutual Respekt',
        releaseid : 'CSMD101',
        embedUrl : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/304457647&color=%236e1111&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true',
        coverUrl : '',
    },
    { 
        title : 'Spartaque playing CSMD039',
        shortInfo : 'Spartaque including CSMD039 in his Supreme Podcast',
        releaseid : 'CSMD039',
        embedUrl : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/215151024&color=%236e1111&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true',
        coverUrl : '',
    },
    { 
        title : 'Richie Santana supporting CSMD048',
        shortInfo : 'Richie Santana charting in his beatport chart CSMD048',
        releaseid : '',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/master/src/Static/SupportCovers/santana9nemy.png?raw=true',
        //https://www.beatport.com/chart/richie-santana-september-picks/367778
    },
    { 
        title : 'Dubfire supporting CSMD048',
        shortInfo : 'Dubfire playing CSMD048 on BBC One Radio',
        releaseid : 'CSMD048',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/master/src/Static/SupportCovers/dubfire9nemybbc.png?raw=true',
        //https://www.bbc.co.uk/programmes/p035f47v
    },
    { 
        title : 'RON COSTA supports CSMD060',
        shortInfo : 'Ron Costa includes in his beatport chart CSMD060',
        releaseid : 'CSMD060',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/master/src/Static/SupportCovers/RonCosta.png?raw=true',
        //https://www.beatport.com/release/viral-cutz/1680250
    },
    { 
        title : 'Boris supporting CSMD044',
        shortInfo : 'Boris supporting CSMD044 on Jewel Kids Alleanza Radio Show',
        releaseid : 'CSMD044',
        embedUrl : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/284246481&color=%236e1111&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true',
        coverUrl : '',
    },
    { 
        title : 'Ilario Alicante supporting CSMD106',
        shortInfo : 'Ilario Alicante supporting CSMD106 at Awakenings Festival starting point 14:00',
        releaseid : 'CSMD106',
        embedUrl : 'https://www.youtube.com/embed/1LZ6Y4H52eA',
        coverUrl : '',
    },
    { 
        title : 'Alex Costa Charts CSMD027',
        shortInfo : 'Alex Costa includes CSMD027 in his latest beatport chart',
        releaseid : 'CSMD027',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/4e5f576da9f1c2cf483ac58615e378bc0014ecc3/src/Static/SupportCovers/CostaNoyzChart.png?raw=true',
    },
    { 
        title : 'Dubfire Supports CSMD028',
        shortInfo : 'Dubfire plays CSMD028',
        releaseid : 'CSMD028',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/4e5f576da9f1c2cf483ac58615e378bc0014ecc3/src/Static/SupportCovers/dubfireRipper.png?raw=true',
    },
    { 
        title : 'Richie Hawtin Plays CSMD044',
        shortInfo : 'Thanks again to Richie Hawtin for playing A++ ( Aplusplus) & Lolla Tek Official - Odd Signals ( Sean Random Remix) in Space Ibiza out now on Consumed Music',
        releaseid : 'CSMD044',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/4e5f576da9f1c2cf483ac58615e378bc0014ecc3/src/Static/SupportCovers/richOddSignalsSeanR.jpg?raw=true',
    },
    
    { 
        title : 'Magnetic Magazine Chart with CSMD044',
        shortInfo : 'Magnetic Magazine Charts CSMD044 A++ & Lolla Tek - Odd Signals (Original Mix) “Odd Signals” A++ and Lolla Tek [Consumed Music] There have been some great collaborative tracks released this year by A++ and Lolla Tek and this is another to add to the list. This tune has a fun bouncy feel because of its swinging bass line and pulsing elements sprinkled throughout. Gotta love that sidechain!',
        releaseid : 'CSMD044',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/4e5f576da9f1c2cf483ac58615e378bc0014ecc3/src/Static/SupportCovers/magneticTopChart.png?raw=true',
    },
    { 
        title : 'Richie Hawtin Plays CSMD044',
        shortInfo : 'Richie Hawtin drops agains A++ & Lolla Tek Official - Odd Signals ( Sean Random Remix) in Croatia',
        releaseid : 'CSMD044',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/4e5f576da9f1c2cf483ac58615e378bc0014ecc3/src/Static/SupportCovers/richOddSignals2.jpg?raw=true',
    },
    { 
        title : 'Dubfire Plays CSMD048',
        shortInfo : 'Dubfire playing in his set from WOMB A++ & Lolla Tek - 9NEMY ( Ovi M & FERRUM Remix) out now on the mighty Consumed Music',
        releaseid : 'CSMD048',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/4e5f576da9f1c2cf483ac58615e378bc0014ecc3/src/Static/SupportCovers/Dubfire9nemy.jpg?raw=true',
    },
    { 
        title : 'Richie Hawtin Plays CSMD048 12.09.15',
        shortInfo : 'Richie Hawtin Plays CSMD048 12.09.15',
        releaseid : 'CSMD048',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/4e5f576da9f1c2cf483ac58615e378bc0014ecc3/src/Static/SupportCovers/Rich9nemy.jpg?raw=true',
    },
    { 
        title : 'Richie Hawtin Plays CSMD048 03.09.15',
        shortInfo : '',
        releaseid : 'CSMD048',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/4e5f576da9f1c2cf483ac58615e378bc0014ecc3/src/Static/SupportCovers/Rich9nemy2.jpg?raw=true',
    },
    { 
        title : 'Richie Hawtin Supporting CSMD048 at Enter Ibiza',
        shortInfo : 'Richie Hawtin supporting Aplusplus & Lolla Tek Official - 9NEMY ( Ovi M & FERRUM Remix) this time at ENTER. in Space Ibiza,out now on the mighty Consumed Music.',
        releaseid : 'CSMD048',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/4e5f576da9f1c2cf483ac58615e378bc0014ecc3/src/Static/SupportCovers/rich9nemy3.jpg?raw=true.jpg',
    },
    { 
        title : 'D-Deck Charts CSMD054',
        shortInfo : 'D-Deck includes CSMD054 in his latest Beatport chart',
        releaseid : 'CSMD054',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/4e5f576da9f1c2cf483ac58615e378bc0014ecc3/src/Static/SupportCovers/ddeckChartYoudontknow.png?raw=true',
    },
    { 
        title : 'Mattew Jay Charts CSMD054',
        shortInfo : 'Mattew Jay includes CSMD054 in his latest Beatport chart',
        releaseid : 'CSMD054',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/4e5f576da9f1c2cf483ac58615e378bc0014ecc3/src/Static/SupportCovers/mattewJayChartYoudontknow.png?raw=true',
    },
    { 
        title : 'Joran Van Pol supporting CSMD028',
        shortInfo : 'Joran Van Pol playing Siles & Aboga - Dutch Boy (Daniel Spanjaard - NL Remix) Fuse Brussels 06/12/2014',
        releaseid : 'CSMD028',
        embedUrl : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/181905201&color=%236e1111&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true',
        coverUrl : '',
    },
    { 
        title : 'Fatima Hajji supports CSMD106',
        shortInfo : 'Fatima Hajji charts on Beatport CSMD106 Kalden Bess, PRML, UNDFND - Basic (David Temessi Remix)',
        releaseid : 'CSMD106',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/4e5f576da9f1c2cf483ac58615e378bc0014ecc3/src/Static/SupportCovers/FatimaChartKalden.png?raw=true',
    },
    { 
        title : 'Carlo Ruetz supports CSMD077',
        shortInfo : 'Carlo Ruetz charts CSMD077 Ovi M - Psycho (Original Mix)',
        releaseid : 'CSMD077',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/4e5f576da9f1c2cf483ac58615e378bc0014ecc3/src/Static/SupportCovers/carloRuetzChartPsycho.png?raw=true',
    },
    { 
        title : 'Mladen Tomic supports CSMD072',
        shortInfo : 'Mladen Tomic includes on his latest Beatport chart CSMD072 J&S Project, Richard Cleber - Finder (Refraction IT Remix)',
        releaseid : 'CSMD072',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/4e5f576da9f1c2cf483ac58615e378bc0014ecc3/src/Static/SupportCovers/mladenChartV1olence.jpg?raw=true',
    },
    { 
        title : 'Someone Else Charts CSMD062',
        shortInfo : 'Someone Else includes CSMD062 in his latest chart on Beatport',
        releaseid : 'CSMD062',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/4e5f576da9f1c2cf483ac58615e378bc0014ecc3/src/Static/SupportCovers/someoneElseChart.png?raw=true',
    },
    { 
        title : 'Richie Hawtin Plays CSMD060',
        shortInfo : 'Richie Hawtin playing CSMD060 in his Essential Mix 30-01-2016 live at Exchange LA.',
        releaseid : 'CSMD060',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/4e5f576da9f1c2cf483ac58615e378bc0014ecc3/src/Static/SupportCovers/richLucy.jpg?raw=true',
    },
    { 
        title : 'Richie Hawtin Plays CSMD060',
        shortInfo : 'Big thanks to Richie Hawtin for playing Aplusplus & Lolla Tek - Lucy Overdrive ( Ovi M Remix) at BBC Radio One. Out now on "VIRAL CUTZ" VA on the mighty Consumed Music',
        releaseid : 'CSMD060',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/4e5f576da9f1c2cf483ac58615e378bc0014ecc3/src/Static/SupportCovers/richLucy1.jpg?raw=true',
    },
    { 
        title : 'Richie Hawtin Charts CSMD060',
        shortInfo : 'Richie Hawtin includes A++, Lolla Tek - Lucy Overdrive (Ovi M Remix) on his latest beatport chart',
        releaseid : 'CSMD060',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/4e5f576da9f1c2cf483ac58615e378bc0014ecc3/src/Static/SupportCovers/richChartLucy.jpg?raw=true',
    },
    { 
        title : 'Richie Hawtin B2B Solomun supporting CSMD048 EGG London',
        shortInfo : 'Richie Hawtin B2B Solomun playing A++ & Lolla Tek - 9NEMY (Ovi M & Ferrum Remix) at EGG London',
        releaseid : 'CSMD048',
        embedUrl : 'https://www.youtube.com/embed/RcHpr6My5DM',
        coverUrl : '',
    },
    { 
        title : 'Joran Van Pol supporting CSMD053',
        shortInfo : 'Joran Van Pol playing in his podcast for Awakenings , Mark Mywords , Daniel Spanjaard - NL , Aplusplus - Continuum (Original Mix) out now on the mighty Consumed Music',
        releaseid : 'CSMD053',
        embedUrl : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/177960561&color=%236e1111&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true',
        coverUrl : '',
    },
    { 
        title : 'Joseph Capriati Supports CSMD048',
        shortInfo : 'Joseph Capriati Supports CSMD048',
        releaseid : 'CSMD048',
        embedUrl : 'https://www.youtube.com/embed/qa5mZ53I9RI',
        coverUrl : '',
    },
    { 
        title : 'Gregor Tresher supports CSMD039',
        shortInfo : 'Gregor Tresher playing Refraction - It - Boundaries (Original Mix) at Watergate, Berlin, 09.05.2015',
        releaseid : 'CSMD039',
        embedUrl : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/206560730&color=%236e1111&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true',
        coverUrl : '',
    },
    { 
        title : 'Deep Dish Supports CSMD028',
        shortInfo : 'Deep Dish playing CSMD028 at Sonica Club in Ibiza starting point at 1:50:00',
        releaseid : 'CSMD028',
        embedUrl : 'https://www.youtube.com/embed/KcpRmSJApOc',
        coverUrl : '',
    },
    { 
        title : 'Steve Mulder supports CSMD090',
        shortInfo : 'Thanks to Steve Mulder for playing CSMD090 Sisko Electrofanatik & kreisel called "Octopus" at Minimal Sessions - Outspoken, Los Angeles (09-12-2016) [MIN - 1:40:00]',
        releaseid : 'CSMD090',
        embedUrl : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/298191883&color=%236e1111&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true',
        coverUrl : '',
    },
    { 
        title : 'The YellowHeads playing CSMD086',
        shortInfo : 'Thanks to The YellowHeads - TYH for playing in their latest podcast CSMD086 Mark Mywords - Paradise " Steve Mulder Remix" [Min - 00:08:00]',
        releaseid : 'CSMD086',
        embedUrl : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/291888878&color=%236e1111&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true',
        coverUrl : '',
    },
    { 
        title : 'Mladen Tomic supports CSMD072',
        shortInfo : 'Mladen Tomic plays CSMD072 Richard Cleber & J&S Project - Finder ( Refraction - It Rework) in Sugar Factory',
        releaseid : 'CSMD072',
        embedUrl : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/259659042&color=%236e1111&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true',
        coverUrl : '',
    },
    { 
        title : 'Spartaque Plays CSMD062',
        shortInfo : 'Spartaque selects Loui Fernandez & Bulaklak - Elpidio // Original Mix (Live at La Fabrique France)',
        releaseid : 'CSMD062',
        embedUrl : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/240976150&color=%236e1111&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true',
        coverUrl : '',
    },
    { 
        title : 'Dense & Pika Support CSMD062',
        shortInfo : 'Dense & Pika drop CSMD062 in the latest Drumcode Podcast recorded live at from Studio Club, Essen',
        releaseid : 'CSMD062',
        embedUrl : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/261310967&color=%236e1111&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true',
        coverUrl : '',
    },
    { 
        title : 'Richie Hawtin Playing CSMD060',
        shortInfo : 'Richie Hawtin Richie Hawtin Playing CSMD060 @ Exchange 1/22/2016 at 03:00',
        releaseid : 'CSMD060',
        embedUrl : 'https://www.youtube.com/embed/5slSnmCvK54',
        coverUrl : '',
    },
    { 
        title : 'Gaga supports CSMD095',
        shortInfo : 'Gaga supports CSMD095 in his March Podcast A++ & Lolla Tek - 9NEMY (Seek One Remix)',
        releaseid : 'CSMD095',
        embedUrl : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/314524108&color=%236e1111&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true',
        coverUrl : '',
    },
    { 
        title : 'Tomy DeClerque supports CSMD100',
        shortInfo : 'Tomy DeClerque supports CSMD100 Bulaklak - Hate Me (Original Mix) in his chart Recorded @ 10th edition of Pulse in Zeleni Gaj',
        releaseid : 'CSMD100',
        embedUrl : 'https://www.youtube.com/embed/f4XruxEYlBU',
        coverUrl : '',
    },
    { 
        title : 'The YellowHeads playing CSMD101',
        shortInfo : 'Thanks to The YellowHeads - TYH for playing in there latest set from Bolero Club (Lisboa) CSMD101 Felix Kröcher - You Don\'t Know But (Raul Mezcolanza Remix) out on Consumed Music [MIN - 26:17]',
        releaseid : 'CSMD101',
        embedUrl : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/368405399&color=%236e1111&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true',
        coverUrl : '',
    },
    { 
        title : 'Fatima Hajji supports CSMD101',
        shortInfo : 'Massive support from Fatima Hajji at Awakenings where she dropped CSMD101 Felix Kröcher - You Don\'t Know But ( Alberto Ruiz & Dani Sbert Remix)',
        releaseid : 'CSMD101',
        embedUrl : 'https://www.youtube.com/embed/85OAzLyBPK8',
        coverUrl : '',
    },
    { 
        title : 'Umek supports CSMD101',
        shortInfo : 'Behind the Iron Curtain by Umek features CSMD101 Felix Krocher - You Don\'t Know But (Mattew Jay Remix)',
        releaseid : 'CSMD101',
        embedUrl : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/299885602&color=%236e1111&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true',
        coverUrl : '',
    },
    { 
        title : 'Sisko Electrofanatik plays CSMD103',
        shortInfo : 'Thanks to Sisko Electrofanatik for dropping my track "Planetary Nebula" in his set from Melkweg Amsterdam out now on Consumed Music',
        releaseid : 'CSMD103',
        embedUrl : 'https://www.youtube.com/embed/Efs-NACaZgc',
        coverUrl : '',
    },
    { 
        title : 'Lolla Tek supports CSMD103',
        shortInfo : 'Lolla Tek plays CSMD103 Alpha Particle Assembly - Perpetual Motion (Original Mix) on her Alleanza Podcast',
        releaseid : 'CSMD103',
        embedUrl : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/389521776&color=%236e1111&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true',
        coverUrl : '',
    },
    { 
        title : 'Pascal Feos B2B The YellowHeads playing CSMD105',
        shortInfo : 'Pascal Feos B2B The YellowHeads playing CSMD105 Alpha Particle Assembly - 9248 (Original Mix)',
        releaseid : 'CSMD105',
        embedUrl : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/442150368&color=%236e1111&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true',
        coverUrl : '',
    },
    { 
        title : 'The YellowHeads playing CSMD105',
        shortInfo : 'The YellowHeads - TYH playing the latest track from Alpha Particle Assembly called "ISO II" in Colombia out now on Consumed Music',
        releaseid : 'CSMD105',
        embedUrl : 'https://www.youtube.com/embed/F2vZSBPQqzM',
        coverUrl : '',
    },
    
    { 
        title : 'Sisko Electrofanatik plays CSMD108',
        shortInfo : 'Sisko Electrofanatik supports CSMD108 from Lolla Tek & Mikel Gil called "Ghost Protocol" (Alpha Particle Assembly) on his latest radio show for Veerus + Maxie Devine called Le Club Culture',
        releaseid : 'CSMD108',
        embedUrl : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/539137047&color=%236e1111&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true',
        coverUrl : '',
    },
    {
        title : 'Richie Hawtin plays CSMD077A',
        shortInfo : 'Big thanks to Richie Hawtin for playing De Dirigenten - Stranger (Original Mix) out now on the mighty Consumed Music',
        releaseid : 'CSMD0771',
        embedUrl : '',
        coverUrl : 'https://github.com/hex25/consumedwebsite/blob/4e5f576da9f1c2cf483ac58615e378bc0014ecc3/src/Static/SupportCovers/richStranger.jpg?raw=true',
    },
    {
        title : 'Gregor Tresher supports CSMD039',
        shortInfo : 'Gregor Tresher playing Refraction - It - Boundaries (Original Mix) at Studio Brussel',
        releaseid : 'CSMD039',
        embedUrl : 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/208243701&color=%23ff5500&auto_play=false&hide_related=false&show_comments=false&show_user=false&show_reposts=false&show_teaser=false&visual=true',
        coverUrl : '',
    },
    {
        title : 'Roberto Capuano plays CSMD103',
        shortInfo : 'Roberto Capuano drops Alpha Particle Assembly - Planetary Nebula (Original Mix) at Cocorico in Italy',
        releaseid : 'CSMD103',
        embedUrl : 'https://www.youtube.com/embed/XT4BmF8TCS4',
        coverUrl : '',
    },
    /* THIS IS A TEMPLATE - PLEASE COPY PASTE FROM { TO }, 
    { 
        title : '',
        shortInfo : '',
        releaseid : '',
        embedUrl : '',
        coverUrl : '',
    },*/
]

supports.sort((a, b) => (a.releaseid < b.releaseid) ? 1 : -1);

export default supports;